name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install uv
        run: |
          pip install uv
      - name: Install dependencies
        run: |
          sudo apt-get install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0 ffmpeg
          uv tool install ruff
          uv sync
      - name: Lint with ruff
        run: |
          ruff check
      - name: Format check with ruff
        run: |
          ruff format --check
